package template;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import template.rules.InheritanceRule;

import java.util.Set;

@Getter
@AllArgsConstructor
@DynamoDBTable(tableName = "CollectionTemplate")
public class CollectionTemplate {

    @Setter
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "partitionKey")
    private String id;
    private String alias, name, productLineId;

    @DynamoDBRangeKey
    @DynamoDBAttribute(attributeName = "sortKey")
    private final String entityType = "TEMPLATE";

    @DynamoDBIgnore
    private Set<CollectionTemplateVersion> collectionTemplateVersions;

    @DynamoDBTypeConvertedJson
    private Set<InheritanceRule> inheritanceRules;
}
