package template.template;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import template.attribute.Attribute;

@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "CollectionTemplate")
@ToString
public class CollectionTemplateVersion {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "partitionKey")
    private String templateId;

    @DynamoDBRangeKey
    @DynamoDBAttribute(attributeName = "sortKey")
    private String sortKey;
    private Integer revision;
    private Long createdAt, publishedAt;
    private String modifiedBy;

    private Attribute<String> title;
    private Attribute<Boolean> async;

    @DynamoDBTypeConvertedEnum
    private CollectionTemplateVersionState state = CollectionTemplateVersionState.DRAFT;

    public enum CollectionTemplateVersionState {
        PUBLISHED,
        DRAFT
    }
}
